<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLBAJcfR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLBAJcfR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLBAJcfR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLBAJcfR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLBAJcfR\App_KernelDevDebugContainer([
    'container.build_hash' => 'LBAJcfR',
    'container.build_id' => '79157f9a',
    'container.build_time' => 1655130582,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLBAJcfR');
