<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOWYvTQd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOWYvTQd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOWYvTQd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOWYvTQd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOWYvTQd\App_KernelDevDebugContainer([
    'container.build_hash' => 'OWYvTQd',
    'container.build_id' => '6af9de12',
    'container.build_time' => 1655132397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOWYvTQd');
