<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLZsmINc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLZsmINc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLZsmINc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLZsmINc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLZsmINc\App_KernelDevDebugContainer([
    'container.build_hash' => 'LZsmINc',
    'container.build_id' => '04911cd4',
    'container.build_time' => 1655128391,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLZsmINc');
